//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalPoint1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RentalPoint1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Rent.rent_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Rent.[From(date)], 
        ///    Rent.[To(date)],
        ///    Rent.[TotalPrice(UAH)],
        ///    Rent.[Deposit]
        ///    from [Order]
        ///        join Rent on Rent.order_id = [Order].order_id
        ///        join Good on Rent.copy_id = Good.good_id
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ActiveRents {
            get {
                return ResourceManager.GetString("ActiveRents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Detail.[Price(UAH)]
        ///    from Detail 
        ///        join [Set] on [Set].detail_id = Detail.detail_id
        ///        join Attachment on Attachment.set_id = [Set].set_id
        ///    where Attachment.attachment_id = @attachment_id;.
        /// </summary>
        internal static string AttachmentPrice {
            get {
                return ResourceManager.GetString("AttachmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    Attachment.attachment_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName,
        ///    Model.ModelName,
        ///    Attachment.Amount,
        ///    Attachment.[TotalPrice(UAH)]
        ///    from Rent
        ///        join Attachment on Attachment.rent_id = Rent.rent_id
        ///        join [Set] on [Set].set_id = Attachment.set_id
        ///        join Detail on Detail.detail_id = [Set].detail_id
        ///        join Product on Product.product_id = [Set].product_id
        ///        join Producer on Producer.producer_id = Detail.p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AttachmentsInfo {
            get {
                return ResourceManager.GetString("AttachmentsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Good.good_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Product.[Price(UAH/day)] - Product.[Price(UAH/day)] * Product.[Discount(%)] / 100 as [Price(UAH/day)],
        ///    Product.[Deposit(UAH)]
        ///    from Good
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer_id = Producer.producer_id
        ///        join Brand on Model.brand_id = B [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AvailableGoodsQuery {
            get {
                return ResourceManager.GetString("AvailableGoodsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Client.client_id,
        ///    Client.LastName,
        ///    Client.FirstName,
        ///    Client.SecondName,
        ///    Client.[Discount(%)] as [Discount]
        ///    from Client
        ///        join [Order] on [Order].client_id = Client.client_id
        ///    where [Order].order_id = @order_id;.
        /// </summary>
        internal static string ClientBillInfo {
            get {
                return ResourceManager.GetString("ClientBillInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Client.client_id, 
        ///    Client.[Discount(%)], 
        ///    DiscountType.DiscountTypeName, 
        ///    Client.LastName,
        ///    Client.FirstName, 
        ///    Client.SecondName, 
        ///    Client.Gender, 
        ///    Client.PhoneNumber, 
        ///    Client.Email, 
        ///    Client.[Address], 
        ///    Client.PostCode, 
        ///    Client.RegistrationDate, 
        ///    Client.[Description] 
        ///    from Client
        ///        join DiscountType on DiscountType.discountType_id = Client.discountType_id
        ///.
        /// </summary>
        internal static string ClientFill {
            get {
                return ResourceManager.GetString("ClientFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    [Set].set_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Detail.[Price(UAH)],
        ///    Detail.Amount,
        ///    Detail.IsReturnable
        ///    from [Set]
        ///        join Product on Product.product_id = [Set].product_id
        ///        join Detail on Detail.detail_id = [Set].detail_id
        ///        join Model on Detail.model_id = Model.model_id
        ///        join Producer on Detail.producer_id = Producer.producer_id
        ///        join Brand on Model.brand_id = Brand.b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompatibleDetails {
            get {
                return ResourceManager.GetString("CompatibleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Detail.detail_id, 
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName, 
        ///    Detail.[Price(UAH)], 
        ///    Detail.Amount, 
        ///    Detail.IsReturnable
        ///    from Detail
        ///        join Model on Model.model_id = Detail.model_id
        ///        join Producer on Producer.producer_id = Detail.producer_id
        ///        join Brand on Brand.brand_id = Model.brand_id
        ///        join ModelType on ModelType.modelType_id = Model.modelType_id
        ///.
        /// </summary>
        internal static string DetailFill {
            get {
                return ResourceManager.GetString("DetailFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Detail.detail_id, Attachment.ReturnAmount
        ///    from Attachment 
        ///        join [Set] on [Set].set_id = Attachment.set_id
        ///        join Detail on Detail.detail_id = [Set].detail_id
        ///    where Attachment.rent_id = @rent_id; 
        ///.
        /// </summary>
        internal static string DetailsToAdd {
            get {
                return ResourceManager.GetString("DetailsToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select [Order].client_id
        ///    from [Order]
        ///        join Rent on Rent.order_id = [Order].order_id
        ///    where Rent.rent_id = @rent_id;.
        /// </summary>
        internal static string GetClientByRent {
            get {
                return ResourceManager.GetString("GetClientByRent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Detail.detail_id, Detail.Amount
        ///    from Detail
        ///        join [Set] on [Set].detail_id = Detail.detail_id
        ///        join Attachment on Attachment.set_id = [Set].set_id
        ///    where Attachment.attachment_id = @attachment_id;
        ///    .
        /// </summary>
        internal static string GetDetailByAttachment {
            get {
                return ResourceManager.GetString("GetDetailByAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Product.[Price(UAH/day)]
        ///    from Product
        ///        join Good on Good.product_id = Product.product_id
        ///    where Good.good_id = @good_id;.
        /// </summary>
        internal static string GoodPrice {
            get {
                return ResourceManager.GetString("GoodPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Rent.rent_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Rent.[From(date)], 
        ///    Rent.[To(date)],
        ///    Rent.[TotalPrice(UAH)],
        ///    Rent.[Deposit]
        ///    from [Order]
        ///        join Rent on Rent.order_id = [Order].order_id
        ///        join Good on Rent.copy_id = Good.good_id
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InactiveRents {
            get {
                return ResourceManager.GetString("InactiveRents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    Model.model_id, 
        ///    ModelType.ModelTypeName,
        ///    Brand.BrandName, 
        ///    Model.ModelName
        ///    from Model
        ///        join Brand on Brand.brand_id = Model.brand_id
        ///        join ModelType on ModelType.modelType_id = Model.modelType_id
        ///.
        /// </summary>
        internal static string ModelFill {
            get {
                return ResourceManager.GetString("ModelFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select Attachment.attachment_id
        ///    from Attachment 
        ///        join Rent on Rent.rent_id = Attachment.rent_id
        ///        join [Order] on [Order].order_id = Rent.order_id
        ///    where [Order].order_id = @order_id;.
        /// </summary>
        internal static string OrderAttachments {
            get {
                return ResourceManager.GetString("OrderAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    Attachment.attachment_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName,
        ///    Model.ModelName,
        ///    Detail.[Price(UAH)],
        ///    Attachment.Amount,
        ///    Attachment.[TotalPrice(UAH)]
        ///    from [Order]
        ///        join Rent on Rent.order_id = [Order].order_id
        ///        join Attachment on Attachment.rent_id = Rent.rent_id
        ///        join [Set] on [Set].set_id = Attachment.set_id
        ///        join Detail on Detail.detail_id = [Set].detail_id
        ///        join Product on Product.pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderAttachmentsBill {
            get {
                return ResourceManager.GetString("OrderAttachmentsBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Good.good_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Product.[Price(UAH/day)],
        ///    Product.[Deposit(UAH)],
        ///    Rent.[From(date)],
        ///    Rent.[To(date)],
        ///    Rent.[TotalPrice(UAH)] as [Price]
        ///    from Rent
        ///        join Good on Good.good_id = Rent.copy_id 
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer_id = Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderBill {
            get {
                return ResourceManager.GetString("OrderBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Rent.rent_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Rent.[From(date)], 
        ///    Rent.[To(date)],
        ///    Rent.[TotalPrice(UAH)],
        ///    Rent.[Deposit]
        ///    from [Order]
        ///        join Rent on Rent.order_id = [Order].order_id
        ///        join Good on Rent.copy_id = Good.good_id
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OrderRents {
            get {
                return ResourceManager.GetString("OrderRents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Product.product_id, 
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName, 
        ///    Product.[Price(UAH/day)], 
        ///    Product.[Discount(%)], 
        ///    Product.[Deposit(UAH)], 
        ///    Product.[Description]
        ///    from Product
        ///        join Model on Model.model_id = Product.model_id
        ///        join Producer on Producer.producer_id = Product.producer_id
        ///        join Brand on Brand.brand_id = Model.brand_id
        ///        join ModelType on ModelType.modelType_id = Mod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductFill {
            get {
                return ResourceManager.GetString("ProductFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    ModelType.ModelTypeName,
        ///    Producer.ProducerName, 
        ///    Brand.BrandName,
        ///    Model.ModelName
        ///    from Product
        ///        join Model on Model.model_id = Product.model_id
        ///        join Producer on Producer.producer_id = Product.producer_id
        ///        join Brand on Brand.brand_id = Model.brand_id
        ///        join ModelType on ModelType.modelType_id = Model.modelType_id
        ///    where Product.product_id = @product_id;
        ///.
        /// </summary>
        internal static string ProductWhereId {
            get {
                return ResourceManager.GetString("ProductWhereId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --drop database [RentalPoint];
        ///--USE [master]
        ///----GO
        ////****** Object:  Database [RentalPoint]    Script Date: 1/26/2021 10:53:14 PM ******/
        ///--CREATE DATABASE [RentalPoint]
        ///-- CONTAINMENT = NONE
        ///-- ON  PRIMARY 
        ///--( NAME = N&apos;RentalPoint&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RentalPoint.mdf&apos; , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
        ///-- LOG ON 
        ///--( NAME = N&apos;RentalPoint_log&apos;, FILENAME = N&apos;C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RentalPointTest {
            get {
                return ResourceManager.GetString("RentalPointTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Rent.rent_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Rent.[To(date)],
        ///    Rent.[Deposit],
        ///    Rent.ReturnCondition,
        ///    Rent.Penalty
        ///    from Rent
        ///        join Good on Rent.copy_id = Good.good_id
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer_id = Producer.producer_id
        ///        join Brand on Model.brand_id = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RentReturnInfo {
            get {
                return ResourceManager.GetString("RentReturnInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    Rent.rent_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Rent.[From(date)], 
        ///    Rent.[To(date)],
        ///    Rent.[TotalPrice(UAH)],
        ///    Rent.[Deposit]
        ///    from Rent
        ///        join Good on Rent.copy_id = Good.good_id
        ///        join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer_id = Producer.producer_id
        ///        join Brand on Model.br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RentsInfoQuery {
            get {
                return ResourceManager.GetString("RentsInfoQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    Attachment.attachment_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName,
        ///    Attachment.Amount,
        ///    Attachment.ReturnAmount,
        ///    Attachment.ReturnPrice
        ///    from Rent
        ///        join Attachment on Attachment.rent_id = Rent.rent_id
        ///        join [Set] on [Set].set_id = Attachment.set_id
        ///        join Detail on Detail.detail_id = [Set].detail_id
        ///        join Product on Product.product_id = [Set].product_id
        ///        join Producer on Produc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReturnAttachments {
            get {
                return ResourceManager.GetString("ReturnAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    [Set].set_id,
        ///    ModelType.ModelTypeName,
        ///    Producer.ProducerName, 
        ///    Brand.BrandName,
        ///    Model.ModelName
        ///    from [Set]
        ///        join Product on Product.product_id = [Set].product_id
        ///        join Detail on Detail.detail_id = [Set].detail_id
        ///        join Model on Model.model_id = Detail.model_id
        ///        join Producer on Producer.producer_id = Detail.producer_id
        ///        join Brand on Brand.brand_id = Model.brand_id
        ///        join ModelType on ModelType.modelType_id = Model.modelTyp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SetsWhereProductId {
            get {
                return ResourceManager.GetString("SetsWhereProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    COUNT(Rent.rent_id) as [Rent amount],
        ///    Client.client_id,
        ///    Client.FirstName,
        ///    Client.LastName,
        ///    Client.SecondName
        ///    from Client
        ///        left join [Order] on [Order].client_id = Client.client_id
        ///        left join Rent on Rent.order_id = [Order].order_id
        ///    group by
        ///        Client.client_id,
        ///        Client.FirstName,
        ///        Client.LastName,
        ///        Client.SecondName
        ///    order by [Rent amount] desc, Client.client_id asc;.
        /// </summary>
        internal static string Statistics_ClientActivity {
            get {
                return ResourceManager.GetString("Statistics_ClientActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    sum(Rent.[TotalPrice(UAH)]) + sum(Attachment.[TotalPrice(UAH)]) as [Paid Price],
        ///    sum(Rent.Penalty) as [Total Penalty],
        ///    Client.client_id,
        ///    Client.FirstName,
        ///    Client.LastName,
        ///    Client.SecondName
        ///    from Client
        ///        left join [Order] on [Order].client_id = Client.client_id
        ///        left join Rent on Rent.order_id = [Order].order_id
        ///        left join Attachment on Attachment.rent_id = Rent.rent_id
        ///    where
        ///        [Order].CancelDate is null
        ///    group by
        ///        Clie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Statistics_ClientPaid {
            get {
                return ResourceManager.GetString("Statistics_ClientPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select
        ///    count(Attachment.attachment_id) as [AttachmentAmount],
        ///    Detail.detail_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName
        ///    from Attachment
        ///        right join [Set] on [Set].set_id = Attachment.set_id
        ///        right join Detail on Detail.detail_id = [Set].detail_id
        ///        join Product on Product.product_id = [Set].product_id
        ///        join Producer on Producer.producer_id = Detail.producer_id
        ///        join Model on Model.model_id = [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Statistics_DetailPopularity {
            get {
                return ResourceManager.GetString("Statistics_DetailPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    count(Rent.rent_id) as [RentAmount],
        ///    Product.product_id,
        ///    ModelType.ModelTypeName, 
        ///    Producer.ProducerName, 
        ///    Brand.BrandName, 
        ///    Model.ModelName
        ///    from Rent
        ///        right join Good on Good.good_id = Rent.copy_id 
        ///        right join Product on Good.product_id = Product.product_id
        ///        join Model on Product.model_id = Model.model_id
        ///        join Producer on Product.producer_id = Producer.producer_id
        ///        join Brand on Model.brand_id = Brand.brand_id
        ///        joi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Statistics_ProductPopularity {
            get {
                return ResourceManager.GetString("Statistics_ProductPopularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select min([From(date)])
        ///    from Rent
        ///    group by order_id
        ///    having order_id = @order_id;.
        /// </summary>
        internal static string TheFirstRentDate {
            get {
                return ResourceManager.GetString("TheFirstRentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    sum(Attachment.[TotalPrice(UAH)]) as [Price],
        ///    sum(Rent.Deposit)
        ///    from Rent
        ///        left join Attachment on Attachment.rent_id = Rent.rent_id
        ///    group by Rent.order_id
        ///    having Rent.order_id = 1;.
        /// </summary>
        internal static string TotalAttPrice {
            get {
                return ResourceManager.GetString("TotalAttPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///    sum(Rent.[TotalPrice(UAH)]) as [RentsPrice],
        ///    sum(Attachment.[TotalPrice(UAH)]) as [AttachmentsPrice],
        ///    sum(Rent.Deposit)
        ///    from Rent
        ///        left join Attachment on Attachment.rent_id = Rent.rent_id
        ///    group by Rent.order_id
        ///    having Rent.order_id = @order_id;.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Attachment set
        ///    Attachment.[TotalPrice(UAH)] = (
        ///        select Attachment.Amount * Detail.[Price(UAH)]
        ///            from Attachment 
        ///            join [Set] on [Set].set_id = Attachment.set_id
        ///            join Detail on Detail.detail_id = [Set].detail_id
        ///        where Attachment.attachment_id = @attachment_id
        ///        )
        ///    where Attachment.attachment_id = @attachment_id;.
        /// </summary>
        internal static string UpdateAttachmentPrice {
            get {
                return ResourceManager.GetString("UpdateAttachmentPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Client set
        ///    [Discount(%)] = @Discount,
        ///    discountType_id = @discountType_id
        ///    where client_id = @client_id;.
        /// </summary>
        internal static string UpdateCLientDiscount {
            get {
                return ResourceManager.GetString("UpdateCLientDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Good set Condition = @Condition
        ///    where good_id in (
        ///        select copy_id from Rent
        ///            where rent_id = @rent_id
        ///    );.
        /// </summary>
        internal static string UpdateGoodCondition {
            get {
                return ResourceManager.GetString("UpdateGoodCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update Rent set 
        ///    Rent.[TotalPrice(UAH)] = (
        ///        select DATEDIFF(day, Rent.[From(date)], Rent.[To(date)]) * (Product.[Price(UAH/day)] - Product.[Price(UAH/day)] * Product.[Discount(%)] / 100)
        ///            from Rent 
        ///                join Good on Rent.copy_id = Good.good_id
        ///                join Product on Product.product_id = Good.product_id
        ///            where Rent.rent_id = @id
        ///    )
        ///    where rent_id = @id.
        /// </summary>
        internal static string UpdateRentPriceAt {
            get {
                return ResourceManager.GetString("UpdateRentPriceAt", resourceCulture);
            }
        }
    }
}
